Added content for hero section
girlscript/EQEquation-Website pull request #111
Opened 2020-10-15 16:01 UTC by ishi0301

2020-10-15 16:19 UTC, saviourcode commented
Issue 1, The first section got padding of right,

<img src="https://user-images.githubusercontent.com/36518515/96157495-fe582080-0f2f-11eb-8f1a-b8b1c30f16a6.png" width="50%">

How it supposed to be,
<img src="https://user-images.githubusercontent.com/36518515/96157593-1d56b280-0f30-11eb-9c4a-11559bde34fa.png" width="50%">

2020-10-15 16:21 UTC, saviourcode commented
Issue 2,
For a mobile view that is a Screen width of less than 770px, the whole section overflows to top and bottom,
<img src ="https://user-images.githubusercontent.com/36518515/96157930-8b02de80-0f30-11eb-8973-6dd36a40d7b4.png" width="50%">

2020-10-15 16:22 UTC, saviourcode commented
@ishi0301 Please correct the above two issues.

2020-10-15 16:26 UTC, saviourcode requested changes

2020-10-15 16:26 UTC, saviourcode commented on style.css
> +  width: 80%;
Remove this width property

2020-10-15 16:26 UTC, saviourcode commented on style.css
> +.container .box {
Make this section responsive

2020-10-15 16:27 UTC, saviourcode commented on style.css
> +  width: 80%;
It will resolve issue 1

2020-10-16 04:10 UTC, ishi0301 commented
@saviourcode Please check.

2020-10-16 08:11 UTC, saviourcode approved these changes
LGTM! Awesome Work!! @ishi0301

2020-10-16 08:18 UTC, ishi0301 commented
Thanks @saviourcode

2020-10-16 13:20 UTC, merged