Fixed the Hero Section
girlscript/EQEquation-Website pull request #92
Opened 2020-10-06 16:16 UTC by Shubham-1105

2020-10-06 16:32 UTC, saviourcode commented
Do that small change. Or else it looks fine.

2020-10-06 16:34 UTC, Shubham-1105 commented
Which change?

2020-10-06 16:35 UTC, saviourcode commented
Check the review

2020-10-06 16:42 UTC, Shubham-1105 commented
review it is not showing

2020-10-06 16:44 UTC, saviourcode requested changes

2020-10-06 16:44 UTC, saviourcode commented on style.css
> +@media screen and (max-width:500px){
The current 100vh for all screen width is okay. Don't reduce it.

2020-10-06 16:45 UTC, saviourcode commented
@Shubham-1105 check now

2020-10-06 16:46 UTC, Shubham-1105 commented
Yes

2020-10-06 17:56 UTC, saviourcode commented
LGTM

2020-10-06 18:00 UTC, Shubham-1105 commented
done

2020-10-20 16:38 UTC, saviourcode commented
@Shubham-1105 We have changed few stuffs in the project. Please feel free to contribute to other open issues and close this PR.

2020-10-29 10:02 UTC, closed without merging